### ISSUE TITLE
[bug]: Grammatical errors in "Echo-SQL Sample"

### ISSUE THREAD

**Issue by ItsRoy69** [keploy/docs#118]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I visit "https://docs.keploy.io/docs/go/quickstart/run-your-first-app-tutorial/#pre-requisites"  , we can see a grammatical error in Keploy Termial where it would,ve been Terminal

### Steps to reproduce

1. Go to https://docs.keploy.io/docs/go/quickstart/run-your-first-app-tutorial/#pre-requisites
2. Scroll down to " Testing using Unit Test File" section
3. You will see
![image](https://user-images.githubusercontent.com/78967360/216965519-5bcef827-69fd-401b-a359-d69dc6d6dc04.png)

### Environment

None

### Version

Cloud

**Comment by nehagup** [comment]
@ItsRoy69 thanks for reporting, please raise a PR.
