### ISSUE TITLE
[bug]: Remove the Copyright @ 2023 footer from the pages as we can see footers are getting repeated

### ISSUE THREAD

**Issue by ItsRoy69** [keploy/docs#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we click on https://docs.keploy.io/docs/go/installation or any other languages instgallation pages we see the footer gets repeated.

![image](https://user-images.githubusercontent.com/78967360/221078605-d8a8f211-295b-4824-b75e-2dd8fb1fdb7a.png)

### Steps to reproduce

1. Go to https://docs.keploy.io/docs/go/installation
2. Scroll down 
3. You'll come across one footer and then next footer again

### Environment

None

### Version

Cloud

**Comment by SanskritiHarmukh** [comment]
@ItsRoy69 I've already created the same issue under Keploy repo for fosshack, thus, closing this one
