### ISSUE TITLE
[bug]: Search Button overrides Keploy logo in lower(galaxy fold) screen sizes.

### ISSUE THREAD

**Issue by Anurag30112003** [keploy/docs#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, the margin of the search button is incorrect and it overrides the logo.
![image](https://user-images.githubusercontent.com/79055093/221358646-63338946-542b-4538-b135-9b3b4db6926e.png)
Expected behavior - 
![image](https://user-images.githubusercontent.com/79055093/221358722-b2e3dfa7-c3ac-44b4-b092-1bee9100334f.png)

### Steps to reproduce

Browser - Chrome
1. Go to https://docs.keploy.io/
2. Right-click and go to inspect page.
3. Press Ctrl + Shift + M  and choose Dimensions as Galaxy Fold (280x653)

Love to work on this.

### Environment

Production

### Version

Cloud

**Comment by akshit5565** [comment]
@Anurag30112003 Please assign this task to me.

**Comment by SoumyadeepOSD** [comment]
I can also work on it. Can you please assign it to me?

**Comment by nehagup** [comment]
@SoumyadeepOSD @akshit5565 can you please verify if this issue still exists?

**Comment by nehagup** [comment]
@SoumyadeepOSD sure you can take it.
