### ISSUE TITLE
[ Documentation request ] Need more data textual data in Why Keploy page.

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/docs#19]
# Brief description

Would be better to have more texual data which infers the graph in `Why Keploy` page which might give addition clarify and help infer the graph.

Page - https://docs.keploy.io/docs/keploy-explained/why-keploy/

**Comment by littleironical** [comment]
@nehagup I would like to work on this issue!

**Comment by nehagup** [comment]
@littleironical sure!!

**Comment by littleironical** [comment]
Created a PR #23
