### ISSUE TITLE
[ Documentation request ] Update documentation for Helm Charts

### ISSUE THREAD

**Issue by anirudhjain75** [keploy/docs#20]
# Brief description

The issue mentioned in helm charts is closed but the documentation isn't updated.

Link - https://docs.keploy.io/docs/server/introduction/#helm-charts-wip

**Comment by littleironical** [comment]
Hi @anirudhjain75 can you specify which issue was mentioned in the helm chart?
I can't see any closed issue in this repo

**Comment by nehagup** [comment]
@littleironical this issue was closed. 
Here's the PR. https://github.com/keploy/docs/pull/21/files#diff-657684e147177e79732e45a9e9294ac83d6793213447bb68bfb8b00716164b6b
