### ISSUE TITLE
[bug]: Link to Keploy Server Docs is missing

### ISSUE THREAD

**Issue by Sonichigo** [keploy/docs#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When Clicking on Keploy Server it directs to this link -> https://docs.keploy.io/docs/keploy-explained/docs/server/introduction 
Which is currently showing ``Page Not Found``

### Steps to reproduce

1. Go to https://docs.keploy.io/docs/keploy-explained/introduction
2. Scroll Down to Keploy SDK section
3. Click on Keploy Server
4. See the Error

### Screenshot 
![image](https://user-images.githubusercontent.com/53110238/187948087-8a9994f2-5d13-4a10-81a6-190097d7e40b.png)

### Version

Cloud

**Comment by nehagup** [comment]
@Sonichigo can you please add a screenshot?

**Comment by mjmanas54** [comment]
I wanna work on this issue but what should be the correct behaviour means what should it show in place of page not find.

**Comment by dinesh-07** [comment]
It seems we have to redirect to the GitHub page of keploy server. https://github.com/keploy/keploy. I cross-checked with other places and that is what existing code is doing

**Comment by Sonichigo** [comment]
@mjmanas54 Dinesh is right.

**Comment by mjmanas54** [comment]
Okk, I would like to work on this can you please assign it to me.

**Comment by dinesh-07** [comment]
It seems like fixed by someone.

**Comment by Sonichigo** [comment]
@dinesh-07 there are a few issues with your commit. Please fix those. @mjmanas54 since he has started the PR issue is being assigned to him. For further ref please wait till issue is being assigned @dinesh-07

**Comment by dinesh-07** [comment]
Fixed as part of https://github.com/keploy/docs/pull/74

**Comment by dinesh-07** [comment]
Close this ticket since the changes are merged.
