### ISSUE TITLE
[bug]: Keploy spelling error

### ISSUE THREAD

**Issue by AnkitKumarvaid** [keploy/docs#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

keploy spelling is incorrect on the home page of website  

![Screenshot (91)](https://user-images.githubusercontent.com/61087993/188285789-d0c1409e-80e1-4c93-8423-624c20be4c95.png)

### Steps to reproduce

keploy spelling is incorrect on the home page of website  

### Version

Cloud

**Comment by VedanthB** [comment]
I'd like to take this up.

**Comment by AnkitKumarvaid** [comment]
@VedanthB  sure you can.  You can also reach out to our developer team on our slack server, general channel

**Comment by VedanthB** [comment]
I have opened PR
