### ISSUE TITLE
[feature]: Top bar color 

### ISSUE THREAD

**Issue by AnkitKumarvaid** [keploy/docs#27]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Top bar color is not matching with keploy theme color which is present on the top

![Screenshot (92)](https://user-images.githubusercontent.com/61087993/188286159-229a3ba4-3f5d-4dab-952d-2f3e790b94ae.png)

### Why should this be worked on?

Top bar color is not matching with keploy theme color

**Comment by VedanthB** [comment]
I'd like to take this up, what should the theme color be changes to ?

**Comment by esvin2661** [comment]
Following on this issue, Has the issue been resolved yet ? If not what color should the change be ?

**Comment by AnkitKumarvaid** [comment]
we are thinking of using orange, black and white color because it matches with our theme color

**Comment by AnkitKumarvaid** [comment]
you can also chat with our developer team on our slack server, #general chat section

**Comment by saksham140023** [comment]
Hi Ankit
Can you assign me this task ?

**Comment by ShivamTyagi12345** [comment]
Sure @saksham140023 . Please go ahead

**Comment by saksham140023** [comment]
> Sure @saksham140023 . Please go ahead

Thank you

**Comment by nehagup** [comment]
@saksham140023 are you still working on this?

**Comment by saksham140023** [comment]
> @saksham140023 are you still working on this?
> 

Yes I'll finish it asap

**Comment by AnkitKumarvaid** [comment]
@saksham140023  are you able to finish it within Hacktober fest season

**Comment by developer-diganta** [comment]
Is anyone working on this? If not, then I can give it a try.

**Comment by nehagup** [comment]
@developer-diganta Feel free to take it up. :)

**Comment by developer-diganta** [comment]
![image](https://user-images.githubusercontent.com/65999534/209775075-6b7e2c4a-8644-4d00-b9bb-7dfc2a73feba.png)
Is this color scheme OK? @nehagup

**Comment by nehagup** [comment]
@developer-diganta Yes, looks good!
