### ISSUE TITLE
[Documentation request]: Adding more topics in the Sidebar  

### ISSUE THREAD

**Issue by littleironical** [keploy/docs#29]
# Brief description

We have asked a few developers to go through our documentation and find the barriers they are facing while understanding Keploy. One of them found it difficult to navigate to different pages!

#  Recommendation

To make the documentation easy for navigation for the developers, we can **increase the number of topics that are available in the sidebar**. Currently, we have to go to the navbar to check for the topics available in the documentation.

### Something like this:
![image](https://user-images.githubusercontent.com/61787056/188509097-6aa294e9-173b-468a-af62-9d352b2e966a.png)

**Comment by littleironical** [comment]
@nehagup as I'm facing one issue while implementing this..

When I go to SDKs section, I'm getting this screen:

![image](https://user-images.githubusercontent.com/61787056/188509445-7ed6033a-f69f-4c08-9e68-7699a65842d8.png)
![image](https://user-images.githubusercontent.com/61787056/188509486-ff753963-cf67-4f1c-b60e-a8f7f4262d2a.png)

### Problem

- As I'm adding topics in the sidebar, where should I put the **SDKs** section?
- And as the SDKs section opens up a new screen without any sidebar, even if we add that in the sidebar, it'll break the flow of the content in the documentation

**Comment by nehagup** [comment]
@littleironical You can show a drop down with 4 subheadings where these SDKs are options

**Comment by littleironical** [comment]
Okay, got it 👍
