### ISSUE TITLE
[feature]: Make the images background transparent

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#32]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

When we read the documentation and encounter any image explaining the above concept or showing an example, it creates a different impact in light and dark mode. 

For example,
As shown below, the image looks perfect in the light mode.

![Light Mode](https://user-images.githubusercontent.com/74777863/188669990-77995445-56a2-4a7a-aee0-efbfde564d5d.png)

But, as soon as I toggle to the dark mode, which is opted comparatively more by users, the images look odd and non-appealing.

![Dark Mode](https://user-images.githubusercontent.com/74777863/188670003-ec1809f0-8243-4c61-9a96-41332bdd9964.png)

Apart from this, 
1. The images could have a better contrast that matches the theme of Keploy. 
2. The image under **Automatically mock Mutations** shows the third-party services. Design an image that shows the logos in a line instead of giving a scattered view.

### Why should this be worked on?

User Experience is important. These changes will help them absorb the content easily.

**Comment by littleironical** [comment]
A solution to this could be making the background of those images transparent

**Comment by Guillergood** [comment]
I can try to work on this, can you assign it to me? Also, which images do you want to have it?

**Comment by SanskritiHarmukh** [comment]
Hi @Guillergood, the images are present [here](https://github.com/keploy/docs/tree/main/static/img), you can have a look corresponding to the ones present in the issue. Assigning it to you.

**Comment by SanskritiHarmukh** [comment]
Hi @Guillergood, below images look pretty weird in the dark mode, can you fix them?

![Screenshot from 2022-10-14 16-34-51](https://user-images.githubusercontent.com/74777863/195832836-8743f063-25a0-4c1a-ba03-ce0df712b062.png)
![Screenshot from 2022-10-14 16-35-55](https://user-images.githubusercontent.com/74777863/195832869-c22ef08c-6a1f-4cb5-b3b0-07b07d4e0a08.png)
![Screenshot from 2022-10-14 16-35-16](https://user-images.githubusercontent.com/74777863/195832851-eb73af20-8fcf-426e-8a5b-2a7b6f61632a.png)
