### ISSUE TITLE
[feature]: Decrease animation speed of the gif

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#33]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

***Problem :*** The 4th feature [Native Interoperability](https://docs.keploy.io/docs/keploy-explained/introduction#4-native-interoperability) has a gif for explanation. The animation speed of it is little high, due to which users aren't able to understand the optimization Keploy offers at first sight.

***Solution:*** Download the gif and decrease the animation speed using any online tool available. 

### Why should this be worked on?

This feature will allow the user to grasp the feature without much strain.

**Comment by metal-oopa** [comment]
Hi @SanskritiHarmukh! Can I work on this issue?

**Comment by Abirham24** [comment]
Hellohttps@SanskritiHarmukh!  could you assign it to me if someone is not working on it?

**Comment by SanskritiHarmukh** [comment]
@metal-oopa go ahead

**Comment by SanskritiHarmukh** [comment]
@metal-oopa are you still working on this?

**Comment by SanskritiHarmukh** [comment]
@Abirham24 you can work on this issue.

**Comment by nakul010** [comment]
Hi @SanskritiHarmukh, I would like to work on this issue. Can you assign it to me?

**Comment by SanskritiHarmukh** [comment]
Yes sure, assigning it to you!
