### ISSUE TITLE
[Documentation request] "Why Keploy?" needs to be more detailed

### ISSUE THREAD

**Issue by littleironical** [keploy/docs#38]
# Brief description

We have asked a few developers to go through our documentation and find the barriers they are facing while understanding Keploy. One of them found it difficult to understand why Keploy should be used while testing APIs

#  Your recommended content

We could add

- The problems of using the conventional methods of API Testing 
- How lengthy was the process before
- And how Keploy solves those issues
- Then the features of Keploy

**Comment by littleironical** [comment]
@AnkitKumarvaid need suggestions from you on this!

**Comment by AnkitKumarvaid** [comment]
Ok Let's have one to one discussion on it
