### ISSUE TITLE
[bug]: fix broken links

### ISSUE THREAD

**Issue by nehagup** [keploy/docs#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The documentation has a few broken links. Need to fix the URLs for the following. 

<img width="1278" alt="Screenshot 2022-09-26 at 5 43 39 PM" src="https://user-images.githubusercontent.com/15074229/192276074-56caf773-e77c-4788-83dd-c1b6ac3e3497.png">

### Steps to reproduce

Click on the paths given in the above screenshot, you'll get a broken page link. 

### Environment

Production

### Version

Local

**Comment by techsnap** [comment]
Hi, I would like to work on this issue. Can you assign this to me?

**Comment by techsnap** [comment]
Thanks! I will open a PR for this in October.

**Comment by nehagup** [comment]
@techsnap are you working on this?

**Comment by techsnap** [comment]
Hi, I have started working on this.
