### ISSUE TITLE
[bug]: Alignment issue in Keploy Home Page (in Firefox browser)

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While accessing documentation of Keploy in Firefox, in the [Home Page](https://docs.keploy.io/) under Resources and Guide section, the operating guide and contribution guide has content which seemed unaligned.
1. The operating guide has bullets and text that can be aligned properly.
![Screenshot from 2022-09-30 20-01-52](https://user-images.githubusercontent.com/74777863/193293032-838740d7-cf9a-4226-8b9c-26370727e16b.png)
2. In the contribution guide, there is much space between the description and 3 contributing ways.
![Screenshot from 2022-09-30 20-02-05](https://user-images.githubusercontent.com/74777863/193293065-97a7cb70-5f66-4961-9c65-80c4588366b9.png)

### Steps to reproduce

In FireFox Browser
1. Go to [Keploy](https://docs.keploy.io/).
2. Scroll down to Resources and Guide and see the result.

### Environment

Production

### Version

Cloud

**Comment by titusjoyson** [comment]
@SanskritiHarmukh Raised a PR for the first item in this issue. [https://github.com/keploy/docs/pull/58](https://github.com/keploy/docs/pull/58)
For the second item it seems to be based on the design. need more details on which approach need to be taken to solve this issue.

Pls have a look

**Comment by littleironical** [comment]
Hi @titusjoyson 
An ideal way to contribute to open-source projects is to inform the maintainers that you'll be doing some tasks. That way the chances of getting your PR ignored are less.
Please keep this in mind for your further contributions. Assigning this to you!
