### ISSUE TITLE
[ Documentation request ] Add Users Profile readme to Documentation

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#50]
# Brief description

We have a sample application for go called [users-profile](https://github.com/keploy/samples-go/tree/main/users-profile) supporting mongodb and gin. Documentation for the same in [Quickstart](https://docs.keploy.io/docs/go/quickstart/) section will be helpful.

#  Your recommended content

Check out this [Readme](https://github.com/keploy/samples-go/blob/main/users-profile/README.md) file of `users-profile`.

**Comment by saksham140023** [comment]
Can you assign this task to me?

**Comment by littleironical** [comment]
Assigning this to you @saksham140023

**Comment by saksham140023** [comment]
Hi 
In which folder should I add user profile readme?

**Comment by littleironical** [comment]
You can add it to the `/docs/go/quickstart` folder and it under the `Qucikstart` sidebar in the documentation

**Comment by saksham140023** [comment]
> You can add it to the `/docs/go/quickstart` folder and it under the `Qucikstart` sidebar in the documentation

okay

**Comment by saksham140023** [comment]
I am getting an error "GREETINGS WORKFLOW RUN FAIL"
Kindly help me regarding this error.

**Comment by ShivamTyagi12345** [comment]
> I am getting an error "GREETINGS WORKFLOW RUN FAIL" Kindly help me regarding this error.

Hey @saksham140023  that's a separate issue that's being worked upon  [here](https://github.com/keploy/docs/issues/59) :)

**Comment by saksham140023** [comment]
> > I am getting an error "GREETINGS WORKFLOW RUN FAIL" Kindly help me regarding this error.
> 
> Hey @saksham140023 that's a separate issue that's being worked upon [here](https://github.com/keploy/docs/issues/59) :)

okay

**Comment by littleironical** [comment]
@ShivamTyagi12345 the Greetings bot is failing in every PR, that's why he's asking
