### ISSUE TITLE
[ Documentation request ] Organize the headings in installation page

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#51]
# Brief description

When you visit [Installation page](https://docs.keploy.io/docs/server/introduction), numbering is assigned to Installation Method heading which is of no need. So, we can remove it.

![Screenshot from 2022-09-30 21-17-14](https://user-images.githubusercontent.com/74777863/193308199-8c56a309-1249-4d8d-ad32-d8a72d1426f0.png)

Rather the sub headings- Helm charts and Docker can be numbered. 

![Screenshot from 2022-09-30 21-19-11](https://user-images.githubusercontent.com/74777863/193308606-e01eec6f-474d-4cf4-9c71-4db51f7e6ed5.png)

The right side bar of this page looks like shown below. Installation methods can also be added in this part.

![Screenshot from 2022-09-30 21-20-50](https://user-images.githubusercontent.com/74777863/193308962-1acd0723-517c-4a12-bfe5-6ce7bc7280af.png)

#  Your recommended content
You can refer to [introduction](https://github.com/keploy/docs/blob/main/docs/server/introduction.md) and [server-installation](https://github.com/keploy/docs/blob/main/docs/server/server-installation.md) Readme files.

**Comment by saksham140023** [comment]
Hi Sanskriti,
Can you assign this task to me?

**Comment by littleironical** [comment]
Go ahead @saksham140023 you can start working on it

**Comment by littleironical** [comment]
@saksham140023 I would request you to work on the other Issue assigned to you first, then we will assign this one to you.
Unassigning you for now.

**Comment by Ritesh-Dabral** [comment]
Hi @SanskritiHarmukh 
I would like to work on this task. 
Can you assign it to me ?
