### ISSUE TITLE
[ Documentation request ] Update the image in How Keploy Works Page

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#52]
# Brief description

There is an image with the old logo of Keploy inside `Record Unique Network Interactions as Test Case` when you visit [How Keploy Works?](https://docs.keploy.io/docs/keploy-explained/how-keploy-works) page which can be updated with a new one.

![Screenshot from 2022-09-30 21-47-35](https://user-images.githubusercontent.com/74777863/193313855-e465f7ec-6af0-4e79-9a12-f756b5d01f29.png)

#  Your recommended content

You can add the below image to [`static/img`](https://github.com/keploy/docs/tree/main/static/img) folder and use it.

![how-works](https://user-images.githubusercontent.com/74777863/193314493-5596a93e-8e3e-48e7-b72d-5bbcc01e6cf0.png)

**Comment by prayatharth** [comment]
Hi @SanskritiHarmukh  Can I do it ?

**Comment by SanskritiHarmukh** [comment]
Yes @prayatharth . Assigning it to you.

**Comment by prayatharth** [comment]
hi i am facing issue with checks for the PR
1. Greetings ------> I have no idea how to deal with this
2. DCO -----> this one I think I could rectify

**Comment by prayatharth** [comment]
@SanskritiHarmukh  I rectified the DCO check but couldn't get past the Greeting check .
Maybe you wanna check this link https://github.com/orgs/community/discussions/25706#discussion-4252038

**Comment by SanskritiHarmukh** [comment]
@nehagup can you suggest something here?
