### ISSUE TITLE
[ Documentation request ] Reduce the content in Gin-Mongo Smaple Doc

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#53]
# Brief description

- When you visit [Gin-Mongo Sample](https://docs.keploy.io/docs/go/quickstart/gin-mongo-quickstart) page, the keploy server `installation methods` are listed again. We can add a redirection link instead of displaying the entire installation process. 

- We can add a [mongoDB](https://www.mongodb.com/) and [PostgreSQL](https://www.postgresql.org/) official website links like done for Gin and Echo for convenience.

![Screenshot from 2022-09-30 22-20-53](https://user-images.githubusercontent.com/74777863/193319065-fdbf2c0a-bb06-4ccb-8660-ffab861853d0.png)
![Screenshot from 2022-09-30 22-23-23](https://user-images.githubusercontent.com/74777863/193319486-aad3a844-a7ec-4ace-adb7-b7b2b9b316d0.png)

- We can remove one of the line from documentation in [Gin-Mongo Sample](https://docs.keploy.io/docs/go/quickstart/gin-mongo-quickstart) 

![Screenshot from 2022-09-30 22-24-59](https://user-images.githubusercontent.com/74777863/193319951-3185498e-baa2-4bdf-a817-533fe5bb8a8e.png)

#  Your recommended content

You can refer to the [`docs/go/quickstart`](https://github.com/keploy/docs/tree/main/docs/go/quickstart) folder.

**Comment by jayeshchoudhary** [comment]
Hey @SanskritiHarmukh I would like to work on this,  can you assign me this issue

**Comment by ShivamTyagi12345** [comment]
Hey @jayeshchoudhary  We appreciate you working on one issue at a time. That way the quality of learning isnt compromised ,

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh @nehagup @ShivamTyagi12345  i can help with it

**Comment by Manoj0Marmat** [comment]
@ShivamTyagi12345 @SanskritiHarmukh @nehagup assign me

**Comment by ShivamTyagi12345** [comment]
Sure :+1:  Kindly avoid tagging multiple maintainers. Good luck with the issue:)

**Comment by Manoj0Marmat** [comment]
@ShivamTyagi12345 okay got it 

> Sure 👍 Kindly avoid tagging multiple maintainers. Good luck with the issue:)

okay got it
