### ISSUE TITLE
[ Documentation request ] Remove SDK Modes content from Go-SDK Integration Page

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#54]
# Brief description

When you visit [`Go SDK/ Integration`](https://docs.keploy.io/docs/go/installation) page you'll see the SDK modes content, which already has a dedicated page to it under [`Docs/Concept/Keploy SDK Modes`](https://docs.keploy.io/docs/concepts/what-are-keploy-sdk-modes). So, rather than importing the SDK Modes part in the Integration page we can just add a redirection link and delete the irrelevant content.

# Your recommended content

Refer to [this file](https://github.com/keploy/docs/blob/main/docs/go/installation.md) for changes.

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh mam i can help with it

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh assign me

**Comment by SanskritiHarmukh** [comment]
Sure

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh @nehagup deleted importing the SDK Modes and added a redirection link

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh @nehagup please review it
