### ISSUE TITLE
[ Documentation request ] Improvements in Java SDK Doc

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#55]
# Brief description
- On navigating to [`How to use the Keploy Java SDK`](https://docs.keploy.io/docs/java/installation) page under  [`Usage`](https://docs.keploy.io/docs/java/installation#usage) -> `Run the testcases` -> `Using command line`, the indentation of steps is irregular. Also, The bullet present in front of 4th point can be removed.

![Screenshot from 2022-09-30 23-32-47](https://user-images.githubusercontent.com/74777863/193332195-b3fdc4f9-576e-42e2-bbc6-bc4ea6b40161.png)

- The [Spring Boot + PostgreSQl sample application](https://docs.keploy.io/docs/java/run-your-first-app-tutorial) can be positioned inside Quickstart section.

- In this [part of java sample app documentation](https://docs.keploy.io/docs/java/run-your-first-app-tutorial#testing-using-unit-test-file) the first point is missing and the indentation of rest of the point description and images are disturbed too.

![Screenshot from 2022-09-30 23-53-25](https://user-images.githubusercontent.com/74777863/193336101-2068f347-2159-4cc4-918b-8e91bf0f0ff3.png)

#  Your recommended content

Refer to the [java](https://github.com/keploy/docs/tree/main/docs/java) and [quickstart](https://github.com/keploy/docs/tree/main/docs/go/quickstart) folders.

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh mam i can help with it

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh assign me
