### ISSUE TITLE
[bug]: fix greetings pipeline in cicd

### ISSUE THREAD

**Issue by nehagup** [keploy/docs#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The greetings action is failing in the pipeline with the following error. 

 
<img width="1487" alt="Screenshot 2022-10-02 at 10 21 52 PM" src="https://user-images.githubusercontent.com/15074229/193466255-7ea1160b-bd36-4bed-870f-e774376ad118.png">

### Steps to reproduce

Make a PR. 

### Environment

Production

### Version

Cloud

**Comment by ShivamTyagi12345** [comment]
Reference to get Started with this Issue :+1: 
- Learn about[ CI/CD](https://about.gitlab.com/blog/2022/04/13/how-to-learn-ci-cd-fast/)
- https://github.com/keploy/keploy/pull/182

**Comment by littleironical** [comment]
> Steps to reproduce
> Make a PR.

The issue still exists after the PR [ci: temp fix the greetings action - keploy#182](https://github.com/keploy/keploy/pull/182)

**Comment by ShivamTyagi12345** [comment]
> > Steps to reproduce
> > Make a PR.
> 
> The issue still exists after the PR [ci: temp fix the greetings action - keploy#182](https://github.com/keploy/keploy/pull/182)

I followed and added the same code of Shubham's  as of now to the workflows :100:
