### ISSUE TITLE
[ Documentation request ] Update Keploy twitter card image

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#71]
# Brief description

As the logo of Keploy has changed, the twitter card in the documentation need to be updated too. Here is the [old](https://github.com/keploy/docs/blob/main/static/img/keploy-logo-twitter-card.png) one. Change the image to a newer one keeping the path same.

#  Your recommended content

You can take reference from [here](https://github.com/keploy/docs/blob/main/static/img/keploy-logo-dark.svg) for the update.

**Comment by ShivamTyagi12345** [comment]
sure @jayeshchoudhary
