### ISSUE TITLE
[ Documentation request ] Fix alignment of keploy logo in nav bar

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#75]
# Brief description

On visiting [Documentation website](https://docs.keploy.io/), you can see that at the navigation bar, keploy logo is not aligned with rest of the nav bar items. So, fix the alignment such that all the items appears in a line.

![Screenshot from 2022-10-06 23-42-28](https://user-images.githubusercontent.com/74777863/194393868-6905d0be-5713-4be1-b8f1-d44a95027e4e.png)

#  Your recommended content

You can refer to [this](https://github.com/keploy/docs/blob/1cfe23a4db27ccbf456bd87231b3712432623470/docusaurus.config.js) file.

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh hello sir i can help with it
