### ISSUE TITLE
[bug]: Image missing in java SDK Spring Boot+ postgreSQL sample section

### ISSUE THREAD

**Issue by AnkitKumarvaid** [keploy/docs#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![keploy-1](https://user-images.githubusercontent.com/61087993/196002317-b43cc647-0f3f-4b74-86fa-7df063ad63cb.png)

### Steps to reproduce

Follow the documentation Run the Java sample application and take screenshots then edit the code of the doc website accordingly.

### Version

Cloud

**Comment by Manoj0Marmat** [comment]
@nehagup assign it to me

**Comment by Manoj0Marmat** [comment]
@nehagup i checked this issue there is no problem with images there is no bug [click here to check](https://docs.keploy.io/docs/java/run-your-first-app-tutorial#testing-using-unit-test-file). kindly close this issue
![Screenshot 2022-10-17 at 10 07 21 AM](https://user-images.githubusercontent.com/85970385/196090663-4737afb5-3f5f-4ead-b863-3ad2e4d24d90.png)

**Comment by nehagup** [comment]
@AnkitKumarvaid can you please verify?

**Comment by AnkitKumarvaid** [comment]
It's correct

**Comment by Manoj0Marmat** [comment]
@nehagup i didn't get that need help
