### ISSUE TITLE
[ Documentation request ] Change the redirection link in typescript button under SDKs  

### ISSUE THREAD

**Issue by SanskritiHarmukh** [keploy/docs#91]
# Brief description

- Clicking on typescript redirects us to a GitHub issue. Now that we have a fully functional SDK support for typescript, the redirection link need to be changed to [this documentation page](https://docs.keploy.io/docs/typescript/installation). Fix this in the [SDKs section](https://docs.keploy.io/application-development) of docs and SDKs Integration section of Resources and Guide in [Home page](https://docs.keploy.io/).

- Remove the text `(WIP)` written after typescript as it is no more work in progress.

![Screenshot from 2022-10-16 10-32-36](https://user-images.githubusercontent.com/74777863/196019123-5543db27-8b72-406b-9a39-e91e06f4b86f.png)

![Screenshot from 2022-10-17 00-14-01](https://user-images.githubusercontent.com/74777863/196052498-fc0ec541-f9ce-4d84-a590-ae50ef0c6730.png)

#  Your recommended content
You can refer to [this](https://github.com/keploy/docs/blob/main/src/components/SDKs.js) file.

**Comment by tanmay-S12** [comment]
hey...pls consider me assigning this issue..would like to work on it

**Comment by SanskritiHarmukh** [comment]
Yeah sure.

**Comment by RJ025** [comment]
hey @SanskritiHarmukh  is this issue solved if not could I work on it.

**Comment by ShivamTyagi12345** [comment]
hey @RJ025  lets give @tanmay-S12  a valid amount of time before we reassign , Meanwhile you may complete the other issue assigned to you:)

**Comment by tanmay-S12** [comment]
> hey @RJ025 lets give @tanmay-S12 a valid amount of time before we reassign , Meanwhile you may complete the other issue assigned to you:)

thanks for coordinating...

**Comment by RJ025** [comment]
yeah yeah for sure no problem @ShivamTyagi12345 @tanmay-S12

**Comment by SanskritiHarmukh** [comment]
@tanmay-S12 I have modified the description and added another task. Please create a PR accordingly.

**Comment by tanmay-S12** [comment]
ohkay...

**Comment by SanskritiHarmukh** [comment]
@tanmay-S12 are you still working on it?

**Comment by Sonichigo** [comment]
Since it's being a long time. Making the issue open for others.

**Comment by anvbey** [comment]
Can you assign this issue to me?

**Comment by Sonichigo** [comment]
@anvbey lmk if you need any help : )
