### ISSUE TITLE
[ Documentation request ] Change Port number to :6789

### ISSUE THREAD

**Issue by ShivamTyagi12345** [keploy/docs#92]
# Brief description
We have updated our UI to start on Port Number 6789. The documentation needs to be updated with the same.
Task :  Find and replace all ports with 6789 [here](https://docs.keploy.io/docs/keploy-explained/introduction/) as well as any other place you can find

#  Your recommended content

Add your recommended content here. Add the content directly to this page or add links to drafts.
Documentation requests that are made without any recommendations could take longer to process.

**Comment by RJ025** [comment]
hey @ShivamTyagi12345  could you please assign this issue to me.

**Comment by ShivamTyagi12345** [comment]
sure . All the best:)

**Comment by RJ025** [comment]
should I also change KEPLOY port (8081) or only 8080

**Comment by nehagup** [comment]
@RJ025 can you please share link/SS of the port change you are talking about?

**Comment by RJ025** [comment]
<img width="464" alt="host" src="https://user-images.githubusercontent.com/93763090/196153453-1dcfbd60-7de1-4c74-810c-c42f50ac5948.png">

here Is the example of port 8081 
do I have to change this also.

**Comment by nehagup** [comment]
@RJ025 yes any link that refers to Keploy UI/Console needs to be updated.

**Comment by imran1509** [comment]
Can i work on this?

**Comment by nehagup** [comment]
@imran1509 issue is already assigned to @RJ025
